name: deepseek
description: A ChatGPT-like AI assistant app
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.2 # State management
  equatable: ^2.0.5 # Value equality
  get_it: ^7.6.0 # Dependency injection
  dio: ^5.3.2 # HTTP client
  shared_preferences: ^2.2.0 # Local storage
  flutter_platform_widgets: ^3.3.5 # Platform-specific widgets
  provider: ^6.0.5 # For theme provider
  intl: ^0.18.1 # Internationalization
  dartz: ^0.10.1
  path_provider: ^2.1.5
  flutter_markdown: ^0.7.7+1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
